const MessageList = {
    "IB1": "Designation already exists",
    "IB2": "Error in initializing system parameter !",
    "IB3": "Message module is not configured",
    "IB4": "Error in initializing messages !",
    "IB5": "User Has already logged into system. Please contact Mobile cash Support Centre on +67727767",
    "IB6": "Old password is incorrect",
    "IB7": "This password is already taken",
    "IB8": "Password changed successfully",
    "IB9": "New password is required",
    "IB10": "Error in loading designations !",
    "IB11": "Error in saving designation !",
    "IB13": "Error! Cannot load user initialization of Bank User creation",
    "IB14": "User logged-in successfully",
    "IB15": "You are already logged in",
    "IB16": "User role created successfully",
    "IB17": "Error in creating user role !",
    "IB18": "User role updated successfully",
    "IB19": "Business Entity User Roles loaded successfully!  ",
    "IB20": "Error! Unable to load User Roles by Business Entity!",
    "IB21": "User Roles loaded successfully by Role ID",
    "IB22": "Error! Unable to load User by Role ID",
    "IB23": "Role permissions loaded successfully",
    "IB24": "Error in loading role permissions !",
    "IB25": "Role permissions saved successfully",
    "IB26": "Error in saving role permissions !",
    "IB27": "Username is required",
    "IB28": "Password is required",
    "IB29": "You are locked out, Please contact Mobile cash Support Centre on +67727777",
    "IB30": "Username or password incorrect",
    "IB31": "Password is incorrect",
    "IB32": "User ID is Required!",
    "IB33": "Old password is required",
    "IB34": "New password is required",
    "IB35": "Confirm password is required",
    "IB36": "New Password and Confirm Password do not match",
    "IB37": "Minimum password length is 8 characters",
    "IB38": "Maximum password length is 20 characters",
    "IB39": "Special characters are not allowed for password",
    "IB40": "Use at least 1 special character(s) for password $ @ & _ ! #",
    "IB41": "Only these special characters are allowed for the password $ @ & _ ! #",
    "IB42": "Use at least 1 numeric character(s) for your password",
    "IB43": "Use at least  1 alpha numeric character(s) for your password",
    "IB44": "Error! Unable to load User For Change password by Admin",
    "IB45": "User for change password by Admin has been loaded",
    "IB46": "Error in changing password !",
    "IB47": "You do not have permissions to change password",
    "IB48": "User session is required",
    "IB49": "User logged-out successfully",
    "IB51": "Business entity is not configured",
    "IB52": "Business entity is inactive",
    "IB53": "Transaction password is required",
    "IB54": "Error in loading user !",
    "IB56": "Error in user unlock !",
    "IB57": "Remarks is required",
    "IB58": "User is not a locked user",
    "IB59": "Remove user is locked",
    "IB60": "Error in loading main menu !",
    "IB61": "User unlocked successfully",
    "IB62": "Error in user unlocking  !",
    "IB63": "You do not have permissions to unlock user",
    "IB64": "Your password has not been sent yet, please contact Mobile cash Support Centre on +67727777",
    "IB65": "Password is expired",
    "IB66": "Error in password expiration !",
    "IB67": "User is not a new user",
    "IB68": "Error in user creation !",
    "IB69": "Role already exists",
    "IB70": "User authentication failed",
    "IB71": "Search results generated successfully",
    "IB72": "User is not in password print status",
    "IB73": "Search results generation failed",
    "IB74": "Password is printed successfully",
    "IB75": "Error in printing password !",
    "IB76": "Assigned user roles loaded successfully",
    "IB77": "Error In loading assigned user roles !",
    "IB78": "Assigned user role/s saved successfully",
    "IB79": "Error in saving assigned user roles !",
    "IB81": "Username Already Exists!",
    "IB82": "User verification is required",
    "IB83": "User is created successfully",
    "IB84": "User is not in verification status",
    "IB85": "User can not be set to awaiting customer verification status",
    "IB86": "User is not in active status",
    "IB87": "User authorized successfully",
    "IB88": "User cancelled successfully",
    "IB89": "User is not authorized to login",
    "IB90": "User inactivated successfully",
    "IB91": "User activated successfully",
    "IB92": "Error occurred while activating the user !",
    "IB93": "Password is required",
    "IB94": "User accepted successfully",
    "IB95": "User rejected successfully",
    "IB96": "User is not in inactive status",
    "IB97": "You can not change your own status",
    "IB98": "You can not login, you are a cancelled user. Please contact Mobile cash Support Centre on +67727777",
    "IB99": "You can not login, you are an inactive user. Please contact Mobile cash Support Centre on +67727777",
    "IB100": "Error in loading password print for the user !",
    "IB101": "Users are loaded successfully for password print",
    "IB102": "Error in loading user details !",
    "IB103": "User is loaded successfully",
    "IB104": "User is updated successfully",
    "IB105": "Error in updating user !",
    "IB106": "User not found.",
    "IB107": "Error in loading Product Information!",
    "IB108": "Product information loaded successfully",
    "IB109": "Error in saving product !",
    "IB110": "Product saved successfully",
    "IB111": "Error in user edit !",
    "IB112": "User is not in cancel status",
    "IB113": "Cancelled user is edited successfully",
    "IB114": "Invalid product code",
    "IB115": "Error in user login !",
    "IB116": "You are not authorized to create users!",
    "IB117": "You are not authorized to edit users!",
    "IB118": "You are not authorized to create customers!",
    "IB119": "Error in loading customer details !",
    "IB120": "Customer loaded successfully",
    "IB121": "Customer ID is Incorrect / Customer Not Found",
    "IB122": "Error in loading customer",
    "IB123": "Error in saving customer !",
    "IB124": "Customer created successfully",
    "IB125": "Business entity code is required",
    "IB126": "Business entity name is required",
    "IB127": "This user does not have access to create products",
    "IB128": "Business entity type is required",
    "IB129": "Branch code is required",
    "IB130": "Branch name is required",
    "IB131": "Customer information could not be found for the given customer number",
    "IB132": "Customer information loaded successfully",
    "IB133": "Error in loading customer information !",
    "IB134": "Your session has expired. Please login to the system again",
    "IB135": "Invalid minimum limit",
    "IB136": "Maximum limit should be greater than the minimum limit",
    "IB137": "Error in USER REJECTION!",
    "IB138": "Error in USER ACCEPTANCE!",
    "IB139": "Error in USER CANCELLATION!",
    "IB140": "Error in USER AUTHORIZATION!",
    "IB141": "Error in USER INACTIVATION!",
    "IB143": "Same user cannot assign user roles",
    "IB144": "No permissions have been selected for saving!",
    "IB145": "Please Enter Customer ID",
    "IB146": "Customer cannot be found for given Customer ID",
    "IB147": "Error in loading customer accounts !",
    "IB148": "Error in loading role creation !",
    "IB149": "Error in navigating to role edit !",
    "IB150": "User is already created for given customer",
    "IB151": "You are restricted to use the system at this time",
    "IB152": "Login time must be greater than the logout time",
    "IB153": "Error in user session module !",
    "IB154": "New bank saved successfully",
    "IB155": "Error in creating a bank !",
    "IB156": "Bank name is required",
    "IB157": "Bank address can not be blank",
    "IB158": "Bank code can not be blank",
    "IB159": "Error in loading bank details !",
    "IB160": "Bank details updated successfully",
    "IB161": "Error in updating bank details !",
    "IB162": "Customer account details loaded successfully",
    "IB163": "Linked accounts saved successfully",
    "IB164": "Error in linking customer accounts !",
    "IB165": "Error in loading customer account link !",
    "IB166": "You do not have access to link customer accounts",
    "IB167": "Customer(s) does not exist!",
    "IB168": "Product(s) does not exist",
    "IB169": "You are trying to access an unauthorized resource. Please log in to the system as a valid user",
    "IB170": "Bank branch created successfully",
    "IB171": "Error in bank branch creation !",
    "IB172": "Error in loading data !",
    "IB173": "Bank branch updated successfully",
    "IB174": "Error in bank branch creation !",
    "IB175": "System is on maintenance mode. We apologize for any inconvenience caused",
    "IB176": "You are not authorized to edit customers",
    "IB177": "Customer updated successfully",
    "IB178": "Customer id is required",
    "IB179": "System parameter details updated successfully",
    "IB180": "Error in updating system parameters !",
    "IB181": "Error in loading fund transfer",
    "IB183": "Security question created successfully",
    "IB184": "Error in security question creation !",
    "IB185": "Security question updated successfully",
    "IB186": "Error in security question creation !",
    "IB187": "Error in loading security question data !",
    "IB188": "Security question data loaded successfully",
    "IB189": "Error in loading account",
    "IB190": "Account loaded successfully",
    "IB191": "Own account transfer details loaded successfully",
    "IB192": "Error in loading account details !",
    "IB193": "Account balance loaded successfully",
    "IB194": "Select a security question",
    "IB195": "Enter a security question answer",
    "IB196": "New cheque book request saved successfully",
    "IB197": "Error in cheque book request !",
    "IB198": "Password is required",
    "IB199": "New Password and Confirm Password Do Not Match",
    "IB200": "Fund Transfer Saved Successfully! Please Enter Your Transaction Password To Complete The Transaction.",
    "IB201": "Unable to complete your transaction. Please contact the support center.",
    "IB202": "You do not have access to link corporate accounts",
    "IB203": "Error! Unable to load Corporate Account Link",
    "IB204": "Error in linking corporate accounts !",
    "IB205": "Sub user entered does not belong to currently logged in Corporate Admin",
    "IB206": "Your transaction has been successful!",
    "IB207": "Your Transaction failed!",
    "IB208": "Unable to complete your transaction. Please contact the support center.",
    "IB209": "Transaction validation failed",
    "IB210": "No active accounts to display for this corporate user",
    "IB211": "Transaction password is incorrect",
    "IB212": "Transaction confirmation failed",
    "IB214": "Incorrect transaction details",
    "IB215": "This Account does not have authority to do this type of transaction",
    "IB216": "Account is not Active!",
    "IB217": "Transaction Amount cannot be less than the minimum limit!",
    "IB218": "Transaction amount exceeds the transaction maximum limit",
    "IB219": "Error in loading transaction details",
    "IB220": "User account list loaded successfully",
    "IB221": "Error in loading user account list !",
    "IB222": "Transaction loaded successfully",
    "IB223": "An error has occurred in uploading the file!",
    "IB224": "Error in loading transaction details",
    "IB225": "Transaction confirmation data loaded successfully",
    "IB226": "Third party account fund transfer details loaded successfully.",
    "IB227": "Error in loading third party account fund transfer",
    "IB228": "Bulk transaction verified successfully",
    "IB229": "Error in bulk transaction verification !",
    "IB230": "Bulk transaction saved successfully and sent for authorization",
    "IB231": "Error in saving bulk transaction !",
    "IB232": "Transaction has been confirmed!",
    "IB233": "Error in loading alerts !",
    "IB235": "Error in report generation !",
    "IB236": "User is not in active status",
    "IB237": "No user roles are available to display",
    "IB238": "Error in updating user role !",
    "IB239": "User verification is successful",
    "IB240": "Error in user verification !",
    "IB241": "You do not have access to modify your own user role",
    "IB242": "User not found",
    "IB243": "You are not a Registered Customer. Please contact Mobile cash Support Centre on +67727777 for more information.",
    "IB244": "Device token number can not be empty",
    "IB245": "Error in device token registration !",
    "IB246": "Customer Already Exists",
    "IB247": "Select password print users",
    "IB248": "Device registration is successful",
    "IB249": "User information not found",
    "IB250": "Device category not found",
    "IB251": "Sub user's transaction limits are not within the corporate admin's transaction limits",
    "IB252": "Unauthorized user",
    "IB253": "Error in transaction control !",
    "IB254": "Device token is updated successfully",
    "IB255": "Error in updating device token !",
    "IB256": "User name or user token is incorrect",
    "IB257": "Error in bulk transfer verification !",
    "IB258": "Bulk transfer verified successfully",
    "IB259": "User is not in password reset status",
    "IB260": "Bulk transfer authorized successfully",
    "IB261": "Error occurred while authorizing bulk transfer !",
    "IB262": "Error occurred while retrieving bulk transfer authorization details !",
    "IB263": "Bulk transfer authorization details loaded successfully",
    "IB264": "Other bank account transfer details are loaded",
    "IB265": "Error in loading other bank account transfer",
    "IB266": "Branch loaded successfully",
    "IB267": "Error in loading branch",
    "IB268": "Sender debit account is required",
    "IB269": "Receiver credit account is required",
    "IB270": "Transaction amount should be greater than zero",
    "IB271": "Narration is required",
    "IB272": "Receiver name is required",
    "IB273": "Please select a bank",
    "IB274": "Please select a branch",
    "IB275": "Invalid maximum limit",
    "IB276": "Invalid file format. You are only permitted to upload csv files",
    "IB277": "Report loaded successfully",
    "IB278": "Bulk transfer rejected successfully",
    "IB279": "Error occurred while rejecting bulk transfer !",
    "IB280": "Error occurred while displaying bulk transfer confirmation details !",
    "IB281": "Error occurred while deleting the account from bulk transfer !",
    "IB282": "Transaction validation failed",
    "IB283": "Error in loading confirmation details",
    "IB284": "Business entity type loaded successfully",
    "IB285": "Error in loading business entity type !  ",
    "IB286": "Beneficiary created successfully",
    "IB287": "Error in beneficiary creation !",
    "IB288": "Beneficiary updated successfully",
    "IB289": "Error in loading beneficiary details !",
    "IB290": "User is not in active status.Please call Mobile cash Support Centre on +67727777.",
    "IB291": "Your Account has been inactivated. Please call Mobile cash Support Centre on +67727777.",
    "IB292": "Please select at least one account to link",
    "IB293": "Your transaction is posted",
    "IB294": "User token can not be null",
    "IB295": "Error in loading product",
    "IB296": "Error in loading cheque book request details",
    "IB297": "Select cheque book collection method",
    "IB298": "The company name field is required",
    "IB299": "The company address field is required",
    "IB300": "The Remarks fields is required",
    "IB301": "Invalid credit account details",
    "IB302": "Selected debit account is not registered!",
    "IB303": "Error occurred while retrieving search results !",
    "IB304": "Search results retrieved successfully",
    "IB305": "Error in loading transaction history details",
    "IB306": "Transaction history loaded",
    "IB307": "Maximum Limit should be greater than minimum account limit.",
    "IB308": "Sub User's Limits are not within Corporate Admin's Limits.",
    "IB309": "Error in loading transaction history details",
    "IB310": "Transaction history details loaded successfully",
    "IB311": "TO DATE' should be greater than 'FROM DATE'",
    "IB312": "Error occurred while retrieving bulk transfer details !",
    "IB313": "Bulk transfer details loaded successfully",
    "IB314": "Error in loading transaction details",
    "IB315": "Transaction details loaded successfully",
    "IB316": "Minimum limit cannot be set as 0 or empty for an account",
    "IB317": "Maximum limit cannot be set as 0 or empty for an account",
    "IB320": "Error in data adding !",
    "IB321": "Error while processing !",
    "IB322": "Shipping company retrieved successfully",
    "IB323": "Error in loading shipping companies !",
    "IB324": "Error while creating shipping company !",
    "IB325": "Error while editing shipping company !",
    "IB326": "Error while getting shipping company !",
    "IB327": "LC saved successfully",
    "IB328": "LC saving failed",
    "IB329": "The user has already logged in. Unable to edit user's roles.",
    "IB330": "Error in creating a clause !",
    "IB331": "Retrieve a Clause",
    "IB332": "Error in getting a clause !",
    "IB333": "Retrieve all clauses",
    "IB334": "Error in getting all clauses !",
    "IB335": "Clause created successfully",
    "IB336": "Clause updated successfully",
    "IB337": "Error in clause creation !",
    "IB338": "Error in edit clause !",
    "IB339": "Error in loading pending transaction",
    "IB340": "Error in loading pending transaction report",
    "IB341": "Error in loading pending transaction details",
    "IB342": "Pending transaction details load successfully",
    "IB343": "Error while selecting user's clauses list!",
    "IB344": "Error while selecting user's beneficiary list!",
    "IB345": "Clause list generated successfully",
    "IB346": "Beneficiary list generated successfully",
    "IB347": "Your transaction was successfully submitted to the bank and will be processed soon",
    "IB348": "Your transaction failed during authorization",
    "IB349": "Error in System Parameter Reading !",
    "IB350": "System Parameter Reading Successful",
    "IB351": "Error in loading user access history data!",
    "IB352": "Error in loading account details !",
    "IB353": "Transaction rejecting failed",
    "IB354": "Your transaction is rejected successfully",
    "IB355": "Transaction has been rejected!",
    "IB356": "Error in loading User Notification(s) !",
    "IB357": "User notification(s) loaded successfully",
    "IB358": "Unable to save user notification(s)",
    "IB359": "User notification(s) saved successfully",
    "IB360": "Unable to send user notification(s)",
    "IB361": "User Notification(s) sent  Successfully",
    "IB362": "Unable to reject user notification(s)",
    "IB363": "User notification rejected successfully",
    "IB364": "Search results generation failed",
    "IB365": "Search results generated Successfully",
    "IB366": "Error in loading user notification(s) history!",
    "IB367": "User notification histories loaded successfully",
    "IB368": "Error in loading user notification details !",
    "IB369": "User notification details loaded successfully",
    "IB370": "Error in loading pending transaction details !",
    "IB371": "Pending transaction details loaded successfully",
    "IB372": "Please select at least one user role to assign",
    "IB373": "Notification senders' list generated successfully",
    "IB374": "Error in Generating Notification Senders' List!",
    "IB375": "Invalid Device Token ID",
    "IB376": "Notification Sender Information cannot be empty",
    "IB377": "Notification Sender ID cannot be Empty!",
    "IB378": "Notification sender status updated successfully",
    "IB379": "Notification sender status updating failed",
    "IB380": "Error in user creation!",
    "IB381": "Notification sender creation saving failed",
    "IB382": "Notification sender created successfully",
    "IB383": "Institution name is required",
    "IB384": "Transaction password failure attempts have exceeded. You are logged out of the system due to security reasons.",
    "IB385": "Bank code already exists",
    "IB386": "Bank branch code already exists",
    "IB387": "Error in loading notification Sender's details!",
    "IB388": "Notification sender details loaded successfully",
    "IB389": "Notification sender updating failed",
    "IB390": "Notification sender updated successfully",
    "IB391": "Error in loading notification sender details!",
    "IB392": "Notification sender details loaded successfully",
    "IB393": "Shipping company created successfully",
    "IB394": "Shipping company updated successfully",
    "IB395": "Error in notification creation!",
    "IB396": "Error in notification creation!",
    "IB397": "Notification creation failed",
    "IB398": "Notification created successfully",
    "IB399": "Notification is required",
    "IB400": "Remarks is required",
    "IB401": "Error in loading LC details! Please try again.",
    "IB402": "Message created successfully",
    "IB403": "Error in loading loans !",
    "IB404": "Error in loading notfication",
    "IB405": "Error in loading loan details !",
    "IB406": "Loan details loaded successfully",
    "IB407": "Error in loading LC details! Please try again.",
    "IB408": "Notification(s) loaded successfully",
    "IB409": "Error in loading notfication(s)",
    "IB410": "Error in loading account statement",
    "IB411": "Error in loading details !",
    "IB412": "Message saved successfully",
    "IB413": "Message data loaded successfully",
    "IB414": "LC authorized successfully",
    "IB415": "Authorized notification(s) details Loaded",
    "IB416": "Error  in loading Authorized notification(s)",
    "IB417": "Notification(s) details loaded successfully",
    "IB418": "Error in loading notification(s) details",
    "IB419": "Notification list loaded successfully",
    "IB420": "Error in generating notification list!",
    "IB421": "Error in authorized notification!",
    "IB422": "Error in rejected notification !",
    "IB423": "Notification(s) rejected successfully",
    "IB424": "Please select a notification",
    "IB425": "Notification authorized successfully",
    "IB426": "Utility providers loaded successfully",
    "IB427": "Utility providers are not available",
    "IB428": "Utility providers are not available",
    "IB429": "Error in loading utility providers !",
    "IB430": "Error in loading link agent control account !",
    "IB431": "Agent control account is linked successfully",
    "IB432": "Invalid utility provider",
    "IB433": "Error in loading utility provider details !",
    "IB434": "Please enter customer number",
    "IB435": "Please enter meter number",
    "IB436": "Meter number length should be 10 Digits",
    "IB437": "Transaction cannot be completed. Please contact Mobile cash support center on +67727777",
    "IB438": "Error in loading charge slab!",
    "IB439": "Error in loading commission slab !",
    "IB440": "Charge slab loaded Successfully",
    "IB441": "Commission slab loaded Successfully",
    "IB442": "Error in linking agent control account !",
    "IB443": "You cannot link multiple accounts as agent control account",
    "IB444": "Charges and commissions have not been set up for one or more transaction types",
    "IB445": "Your Transaction has been successful and needs to be authorized",
    "IB446": "Error in loading agent charges and commissions!",
    "IB447": "Agent transaction charges are saved successfully",
    "IB448": "Agent transaction commissions are saved successfully",
    "IB449": "Error in loading user status history report!",
    "IB450": "Error in loading user status details!",
    "IB451": "User status details loaded successfully",
    "IB452": "Please select a user",
    "IB453": "Error in loading notification view!",
    "IB454": "Error in loading utility bill Payment Details!",
    "IB455": "There are no utility bill payments to reconcile",
    "IB456": "This customer id does not belong to an agent",
    "IB457": "Error in loading logged users details!",
    "IB458": "Error in loading logged users !",
    "IB459": "Logged users loaded successfully",
    "IB460": "Error in loading logged Users!",
    "IB461": "Selected items reconciled successfully",
    "IB462": "Selected items cannot be reconciled",
    "IB463": "Product(s) does not exist or no local currency accounts available to display",
    "IB464": "Notification(s) loaded successfully",
    "IB465": "Error in loading Notification(s)!",
    "IB466": "Error in loading notification(s) details !",
    "IB467": "Notification(s) details loaded successfully",
    "IB468": "Account details loaded successfully",
    "IB469": "Error in loading account details!",
    "IB470": "Error in loading transaction history!",
    "IB471": "Error in loading dashboard!",
    "IB476": "Cheque book request cannot be authorized",
    "IB477": "Error in loading My TT!",
    "IB478": "Error in creating My TT!",
    "IB479": "SWIFT Code validation failed",
    "IB480": "SWIFT Code validated successfully",
    "IB481": "Error in creating My TT!",
    "IB482": "My TT saved successfully",
    "IB483": "Error in saving My TT!",
    "IB484": "The send money from my account field is required",
    "IB485": "Transaction Amount field is required",
    "IB486": "Currency field is required",
    "IB487": "Beneficiary account number field is required",
    "IB488": "Beneficiary name field is required",
    "IB489": "Beneficiary address field is required",
    "IB490": "Related reference field is required",
    "IB491": "SWIFT Code field is required",
    "IB492": "Please validate SWIFT Code",
    "IB493": "Purpose field is required",
    "IB494": "The sender to receiver message field is required",
    "IB495": "Remarks field is required",
    "IB496": "Invalid file format. You are not permitted to upload executable (.exe) files",
    "IB497": "Error in loading my TT confirmation Data !",
    "IB498": "My TT confirmation data loaded successfully",
    "IB499": "My TT confirmation saving failed",
    "IB500": "My TT Confirmation Failed!",
    "IB501": "My TT is completed successfully",
    "IB502": "My TT validation failed",
    "IB503": "My TT details are incorrect",
    "IB504": "Error in loading My TT Confirm view details",
    "IB505": "Error in loading Reference numbers",
    "IB506": "My TT reject failed",
    "IB507": "My TT is rejected successfully",
    "IB508": "Error in loading My TT !",
    "IB509": "My TT list loaded successfully",
    "IB510": "File opening failed",
    "IB511": "Unable to authorize LC",
    "IB519": "Error in loading Trade Finance dashboard !",
    "IB520": "Trade Finance dashboard loaded successfully",
    "IB521": "Error in loading LC report loading",
    "IB522": "LC report loaded successfully",
    "IB527": "Error in loading show messages report",
    "IB528": "Show messages report loaded successfully",
    "IB529": "Error in loading guarantee report",
    "IB530": "Guarantee report loaded successfully",
    "IB531": "Guarantee submitted successfully. Customer Reference No:",
    "IB532": "LC submitted successfully. Customer Reference No:",
    "IB533": "Please enter mobile number.",
    "IB534": "Error! PDF file cannot be generated",
    "IB535": "Transaction Confirmed! Your PDF file is generated successfully!",
    "IB536": "Error in loading user permissions",
    "IB537": "User permission loaded successfully",
    "IB538": "User login Passcode successfully registered",
    "IB539": "Error in user login",
    "IB540": "Error ! Passcode cannot be registered",
    "IB541": "Passcode successfully registered",
    "IB542": "Please enter your Passcode",
    "IB543": "Your account is inactive. Please contact Mobile cash Support Centre on +67727777",
    "IB545": "Invalid PIN",
    "IB546": "LC rejected successfully. Customer Reference No :",
    "IB547": "Guarantee rejected successfully. Customer Reference No:",
    "IB548": "Unable to connect to top-up server at the moment. Please try again later",
    "IB549": "Transaction amount should be greater than the minimum transaction amount",
    "IB550": "Transaction amount should be less than the maximum transaction amount",
    "IB551": "Error in loading account balance!",
    "IB552": "Load account balance",
    "IB553": "Sender mobile cash account is not in active status",
    "IB554": "Error has been occurred while opening password print and reprint report",
    "IB555": "Password print and reprint report generated successfully",
    "IB556": "Receiver mobile cash account is not in active status",
    "IB557": "Transaction Amount cannot be greater than the service provider's maximum limit",
    "IB558": "Transaction Amount cannot be less than the service provider's minimum limit",
    "IB559": "Error occured while creating mobile cash user",
    "IB560": "Request Mobile Cash User Creation Verification Code generation failed",
    "IB561": "Request Mobile Cash User Creation Verification Code generation failed",
    "IB562": "Request Mobile-Cash User Creation Verification Code generation successfully",
    "IB563": "The Name fields is required",
    "IB564": "The Name fields exceed max length",
    "IB565": "The Address fields is required",
    "IB566": "The Address fields exceed max length",
    "IB567": "The Date Of Birth fields is required",
    "IB568": "Date of birth should be less than the current date",
    "IB569": "The Mother Maiden Name fields is required",
    "IB570": "The Mother Maiden Name fields exceed max length",
    "IB571": "The Identification Type fields is required",
    "IB572": "Mobile-Cash Account Number is required",
    "IB573": "Transaction Amount should be greater than 0",
    "IB574": "The Identification Type fields not define type",
    "IB575": "The Identification Number Name fields is required",
    "IB576": "The Identification Number fields exceed max length",
    "IB577": "The Mobile Number fields is required",
    "IB578": "The Mobile Number fields exceed max length",
    "IB579": "The PIN Code fields is required",
    "IB580": "The PIN Code fields exceed max length",
    "IB581": "PIN code and confirm PIN code does not match",
    "IB582": "Mobile-Cash user is created successfully",
    "IB583": "Mobile-Cash account already created for your mobile number",
    "IB584": "Error occurred while loading Mobile-Cash user activation",
    "IB585": "Error occurred while loading Mobile-Cash user inactivation",
    "IB586": "Error occurred while retrieving Mobile-Cash user details",
    "IB587": "Mobile-Cash user successfully created",
    "IB588": "Mobile-Cash user details retrieved successfully",
    "IB589": "Error occured while activating the Mobile-Cash user",
    "IB590": "Mobile-Cash user is activated successfully",
    "IB591": "Error occurred while inactivating the Mobile-Cash user",
    "IB592": "Mobile-Cash user is inactivated successfully",
    "IB593": "Money transfer requested Mobile-Cash account not available. Please check Mobile-Cash account number.",
    "IB594": "Mobile-Cash Account is inactive",
    "IB595": "Error occurred while activating/inactivating the Mobile-Cash user",
    "IB596": "Mobile-Cash account balance is insufficient to proceed the transaction",
    "IB597": "Your PIN code is incorrect",
    "IB598": "Your PIN code is expired",
    "IB599": "Mobile-Cash to Mobile-Cash fund transfer transaction saved successfully and confirm to complete the transaction.",
    "IB600": "Error occurred while saving Mobile-Cash to Mobile-Cash fund transfer.",
    "IB601": "Error occurred while unlocking the Mobile-Cash user",
    "IB602": "Mobile-Cash user is unlocked successfully",
    "IB603": "Error occurred while resetting the PIN",
    "IB604": "PIN reset successfully",
    "IB605": "Error occurred while loading Mobile-Cash user unlock",
    "IB606": "Error occurred while loading PIN reset",
    "IB607": "Mobile-Cash account balance loaded successfully",
    "IB608": "Error occured while loading Mobile-Cash accounts",
    "IB609": "Your transaction is successfully completed but an error occured while sending email notification",
    "IB610": "Mobile-Cash account transactions loaded successfully",
    "IB611": "Error occured while loading Mobile-Cash account transactions",
    "IB612": "Error occurred while loading cash withdrawal from Mobile-Cash",
    "IB613": "Error occurred while saving cash withdrawal from Mobile-Cash",
    "IB614": "Cash withdrawal from Mobile-Cash saved successfully and verification PIN code has been sent to mobile",
    "IB615": "Error occurred while retrieving cash withdrawal from Mobile-Cash details",
    "IB616": "Cash withdrawal from Mobile-Cash confirmed successfully",
    "IB617": "Error occurred while confirming cash withdrawal from Mobile-Cash",
    "IB618": "Cash withdrawal from Mobile-Cash details retrieved successfully",
    "IB619": "OTP Module Loaded successfully",
    "IB620": "Error in OTP Module Loading",
    "IB621": "OTP has been resent successfully",
    "IB622": "Error occurred while resending OTP",
    "IB623": "Mobile-Cash Account fund transfer details are loaded",
    "IB624": "Mobile-Cash account fund transfer loading failed",
    "IB625": "Cash withdrawal requested Mobile-Cash account is not available. Please check the Mobile-Cash account number.",
    "IB626": "Mobile-Cash to Mobile-Cash Fund Trasfer Confirmed Successfully",
    "IB627": "Mobile-Cash to Mobile-Cash Fund Transfer Confirmation Failed",
    "IB629": "Transaction validation failed",
    "IB630": "OTP session expiration completed successfully.",
    "IB631": "Error occured while expiring OTP sessions.",
    "IB632": "This agent does not have an agent control account",
    "IB633": "This Mobile-Cash user does not have a Mobile-Cash control account",
    "IB634": "This agent control account is not in active status to perform the transaction",
    "IB635": "Mobile-Cash Account is not an active status",
    "IB636": "OTP Generation Module updated successfull",
    "IB637": "Error in OTP Generation Module updated",
    "IB638": "Transaction Failed. Please setup sender Mobile-Cash control account",
    "IB639": "Transaction Failed. Please setup receiver Mobile-Cash control account",
    "IB640": "Mobile-Cash to Mobile-Cash Fund Transfer only allowed to Mobile-Cash users",
    "IB641": "Mobile-Cash control account not found. Setup Mobile-Cash account to continue",
    "IB642": "Setup transaction charge amounts for the transaction type",
    "IB643": "Setup transaction commission amounts for the transaction type",
    "IB644": "Error in existing Mobile-Cash user verification",
    "IB645": "Existing Mobile-Cash user verification successful",
    "IB-646": "Invalid mobile number",
    "IB647": "Agent control account has not been registered in internet banking",
    "IB648": "Transaction verification is successful. Please confirm to complete the transaction",
    "IB649": "Please enter correct Mobile-Cash account",
    "IB650": "Transaction verification is successful. Please confirm the transaction",
    "IB651": "Sender Mobile-Cash account and the receiver Mobile-Cash account cannot be the same. Please enter valid Mobile-Cash account number.",
    "IB652": "Transaction Failed. Mobile-Cash control account is not in active status",
    "IB653": "Error occurred while loading top-up Mobile-Cash",
    "IB654": "Error occurred while confirming top-up Mobile-Cash",
    "IB655": "Top-up Mobile-Cash confirmed successfully",
    "IB656": "Top-up Mobile-Cash transaction saved successfully. Click confirm to proceed",
    "IB657": "Error occurred while submitting top-up Mobile-Cash",
    "IB658": "Top-up requested Mobile-Cash account is not available. Please check the Mobile-Cash account number.",
    "IB659": "Error in loading cash deposit!",
    "IB660": "Cash Deposit Saved Successfully",
    "IB661": "Cash deposit details loaded successfully.",
    "IB662": "Error in loading cash deposit.",
    "IB663": "Error occurred while verifying top-up Mobile-Cash",
    "IB664": "Cash Deposit failed!.",
    "IB665": "Error occured while loading confirmation summary",
    "IB666": "Cash Withdrawal Submitted Successfully. Please Enter OTP to Confirm the Transaction",
    "IB667": "Error Occured While Submitting Cash Withdrawal",
    "IB668": "Cash Withdrawal Failed",
    "IB669": "Error in loading Cash Withdrawal",
    "IB670": "Error occurred while confirming cash deposit",
    "IB671": "Error occurred while saving cash deposit.",
    "IB672": "Cash Withdrawal Confirmed Successfully",
    "IB673": "Error Occured While Confirming Cash Withdrawal",
    "IB674": "Error in Load Cash Withdrawal",
    "IB675": "Mobile-Cash User KYC Document Approved Successfully",
    "IB676": "KYC document has not approved for the given Mobile-Cash Account Number. Please contact the Bank",
    "IB677": "Cash Deposit confirmed successfully",
    "IB678": "Mobile-Cash user has already logged in to the system.",
    "IB679": "Net total amount cannot be zero or less than zero",
    "IB680": "Customer Account Number does not exist",
    "IB681": "Account holder does not have agency banking transaction facility. Please contact bank to request permission",
    "IB682": "Customer mobile number not found. Please contact bank.",
    "IB683": "Account holder mobile number has not verified. Please contact bank.",
    "IB684": "Welcome to Mobile cash. Your secure PIN: OTP. Please dial *456# to enjoy the convenience of mobile cash.",
    "IB685": "You have received CUR AMT from",
    "IB686": "You have sent CUR AMT to",
    "IB687": "You have received CUR AMT to your Mobile-Cash at AGENT - iZi Cash",
    "IB688": "Dear Customer, Your mobile cash account PIN has been reset. You can login/transact using the PIN:",
    "IB689": "You have successfully withdrawn CUR AMT from your Mobile-Cash at AGENT - iZi Cash",
    "IB690": "Your Mobile-Cash cash withdrawal OTP is:",
    "IB691": "Your PROD Account iZi Cash Withdrawal OTP is",
    "IB692": "You have successfully withdrawn CUR AMT from PROD Account ACC at AGENT - iZi Cash",
    "IB693": "You have successfully deposited CUR AMT to PROD Account ACC at AGENT - iZi Cash",
    "IB694": "Thank you for your payment of CUR AMT for SERPRO. Ref No:",
    "IB695": "PIN Code is required.",
    "IB696": "PIN Code length should be 4 digits",
    "IB697": "Account Number length should be 12 digits",
    "IB698": "Mobile-Cash User already registered.",
    "IB699": "Mobile-Cash User not found.",
    "IB700": "Error in loading merchant,Please try again.",
    "IB701": "Unable to load commission frequency types",
    "IB702": "Error in commission frequency types loading,Please try again.",
    "IB703": "Commission frequency types details retrieved successfully.",
    "IB704": "Merchant account is not available. Please check the account number.",
    "IB705": "Merchant account is inactive",
    "IB706": "Merchant successfully saved.",
    "IB707": "Error occurred while creating merchat.",
    "IB708": "Given PIN cannot be accepted",
    "IB709": "Merchant not found. Please enter the correct Merchant Code",
    "IB715": "Your Verification Code is expired",
    "IB716": "Your Verification Code is incorrect",
    "IB717": "Error has been occurred while loading Mobile-Cash Transaction report.",
    "IB718": "No Results Found.",
    "IB719": "Mobile-Cash Transaction report generated successfully.",
    "IB720": "Error occurred while loading Mobile-Cash users.",
    "IB721": "Mobile-Cash user search result loaded successfully.",
    "IB722": "Error occurred while loading agents.",
    "IB723": "Agents loaded successfully.",
    "IB724": "Welcome to Mobile cash. Your account verification code is :",
    "IB725": "Exisiting Mobile-Cash User Verfication Code Successfully Generated.",
    "IB726": "Existing Mobile-Cash User Verification Code Genrate Failed.",
    "IB727": "Error in Existing Mobile-Cash User Verfication Code Generate",
    "IB728": "Registered IB Customers Report generated successfully!",
    "IB729": "Error has been occured while opening Registered IB Customers report!",
    "IB730": "Error occured while retrieving Registered IB Customers!",
    "IB731": "Transactions loaded successfully!",
    "IB732": "Error in loading Transactions!",
    "IB733": "Mobile-Cash Transaction Charges Setup Successfully",
    "IB734": "Mobile-Cash Transaction Charges Setup Failed!",
    "IB735": "Mobile-Cash account details loaded successfully",
    "IB736": "Mobile-Cash Account Loading Failed!",
    "IB737": "Error in loading Mobile-Cash account!",
    "IB738": "Transaction charges have not been set up for one or more transaction types",
    "IB739": "Error in setup Mobile-Cash account transaction charges",
    "IB740": "Mobile-Cash transaction charges are saved successfully",
    "IB741": "Error has been occurred while loading Agent wise Transaction report.",
    "IB742": "Agent wise Transaction report generated successfully.",
    "IB743": "Error has been occurred while loading Merchant wise Transaction report.",
    "IB744": "Merchant wise Transaction report generated successfully.",
    "IB745": "Unable To Load IB Statistics Report",
    "IB746": "Invalid Choice. Please Try Again.",
    "IB747": "First name cannot be empty.",
    "IB748": "First name cannot be empty or contain only special characters/digits.",
    "IB749": "Last name cannot be empty.",
    "IB750": "Last name cannot be empty or contain only special characters/digits.",
    "IB751": "Date of birth cannot be empty.",
    "IB752": "Invalid date of birth.",
    "IB753": "Date of birth should be less than the current date.",
    "IB754": "Invalid inputs for Date of birth field.",
    "IB755": "Please enter receiver's Mobile-Cash account.",
    "IB756": "Receiver's Mobile-Cash cannot contain characters/special characters.",
    "IB757": "The Mobile-Cash account you entered does not exist.",
    "IB758": "Invalid amount.",
    "IB759": "Merchant code cannot be empty.",
    "IB760": "Invalid merchant code.",
    "IB761": "Reference number cannot be empty.",
    "IB762": "Mobile number cannot be empty.",
    "IB763": "Invalid mobile number.",
    "IB764": "Mobile number cannot contain characters/special characters.",
    "IB765": "Mobile number should be 7 digits.",
    "IB766": "Invalid utility provider.",
    "IB767": "Invalid PIN.",
    "IB768": "PIN cannot be empty.",
    "IB769": "PIN should be 4 digits.",
    "IB770": "PIN cannot contain characters/special characters.",
    "IB771": "Given PIN cannot be accepted.",
    "IB772": "Given PIN and confirm PIN do not match.",
    "IB773": "Transaction failed.",
    "IB774": "Transaction not Allowed. Transaction exceeds the Mobile-Cash maximum limit allowed",
    "IB775": "Transaction not Allowed. Transaction below the Mobile-Cash minimum limit allowed",
    "IB776": "Error occurred while loading merchants.",
    "IB777": "Merchant search result loaded successfully.",
    "IB778": "Mobile-Cash transaction limit template successfully saved.",
    "IB779": "Unable to save Mobile-Cash transaction limit template.",
    "IB780": "You have received CUR AMT from CUSNAME Account ACC",
    "IB781": "Your age should be completed 18 to create mobile cash account",
    "IB800": "Mobile-Cash transaction limit charges successfully added.Please save the changes.",
    "IB801": "Your transaction is successfully completed but an error occured while sending sms notification",
    "API-5": "Sender's Account Number is invalid",
    "API-6": "Receiver's Account Number does not exist.",
    "API-7": "Sender's account and Receiver's account cannot be the same.",
    "API-8": "Sender's  account is not in  Active status.",
    "API-9": "Cannot process your request due to a problem with the receiver's account. Please contact the bank.",
    "API-11": "Sender currency does not match with the receiver currency.",
    "API-12": "Insufficient account balance.",
    "API-21": "Cannot process your request due to an internal issue. Please try again later.",
    "API-33": "Account balance will be less than the account minimum balance. Please try with a less transaction amount.",
    "API-34": "You cannot process this transaction. Your account has been closed.",
    "API-35": "You cannot process this transaction. Your account is a non performing account.",
    "IB802": "Mobile-Cash account successfully closed.",
    "IB803": "Unable to close Mobile-Cash account.",
    "IB804": "Error in Mobile-Cash account closure.",
    "IB805": "Error has been occurred while loading Register Mobile-Cash Customer report.",
    "IB806": "Register Mobile-Cash Customer report generated successfully.",
    "IB807": "Error has been occurred while loading Merchant Listing report.",
    "IB808": "Merchant Listing report generated successfully.",
    "IB809": "Error has been occurred while loading Agent Listing Customer report.",
    "IB810": "Agent Listing report generated successfully.",
    "IB811": "OTP Generated Successfully.",
    "IB812": "Error in loading OTP Information.",
    "IB813": "Unable to Change PIN. The PIN already used.",
    "IB814": "Error occurred while creating savings purpose.",
    "IB815": "Savings Purpose saved successfully.",
    "IB816": "Error in loading savings purpose.",
    "IB817": "Savings Purpose updated successfully.",
    "IB818": "Error occurred while updating savings purpose.",
    "IB819": "Successfully load savings purpose.",
    "IB820": "Savings Purpose Already Exists.",
    "IB821": "Error occurred while loading goal setting.",
    "IB822": "Error occurred while creating savings goal.",
    "IB823": "Error occurred while updating savings goal.",
    "IB824": "Savings Goal saved successfully.",
    "IB825": "Savings Goal updated successfully.",
    "IB826": "Successfully load savings goal.",
    "IB827": "Savings Goal cancelled successfully.",
    "IB828": "Error occurred while inactivating savings goal.",
    "IB829": "Error occurred while creating Mobile-Cash savings user.",
    "IB830": "Error occurred while retrieving Mobile-Cash savings user details.",
    "IB831": "Error occurred while approving Mobile-Cash savings user.",
    "IB832": "Mobile-Cash Savings User KYC Approved Successfully.",
    "IB833": "Successfully load Business Entity Segement.",
    "IB834": "Error in loading Business Entity Segement.",
    "IB835": "Successfully load System Financial Service.",
    "IB836": "Error in loading System Financial Service.",
    "IB837": "Successfully load Disability Indicators.",
    "IB838": "Error in loading Disability Indicators.",
    "IB839": "Successfully load Disability Types.",
    "IB840": "Error in loading Disability Types.",
    "IB841": "There is no Mobile-Cash savings account. Please setup Mobile-Cash savings account first.",
    "IB842": "Successfully load Mobile-Cash savings account.",
    "IB843": "Gender cannot be empty.",
    "IB844": "Gender cannot be empty or contain only 1 or 2",
    "IB845": "Successfully load promotion code details.",
    "IB846": "Error in loading promotion code details.",
    "IB847": "Mobile-Cash to Saving Account transfer details loaded successfully.",
    "IB848": "Saving Account to Mobile-Cash transfer details loaded successfully.",
    "IB849": "Error occurred while loading Mobile-Cash saving notification.",
    "IB850": "Notification saved successfully.",
    "IB851": "Error occurred while creating notification.",
    "IB852": "Notification updated successfully.",
    "IB853": "Error occurred while updating notification.",
    "IB854": "successfully load Mobile-Cash saving notification types.",
    "IB855": "error in loading Mobile-Cash saving notification types.",
    "IB856": "successfully load Mobile-Cash saving notification event.",
    "IB857": "error in loading Mobile-Cash saving notification event.",
    "IB858": "successfully load Mobile-Cash saving notification action.",
    "IB859": "error in loading Mobile-Cash saving notification action.",
    "IB860": "successfully load Mobile-Cash saving notification channel.",
    "IB861": "error in loading Mobile-Cash saving notification channel.",
    "IB862": "successfully load notification.",
    "IB863": "error in loading notification.",
    "IB864": "successfully load Mobile-Cash saving notification template.",
    "IB865": "error in loading Mobile-Cash saving notification template.",
    "IB866": "Notification template saved successfully",
    "IB867": "Error occurred while creating notification template.",
    "IB868": "Error occurred while loading notification template.",
    "IB869": "Notification template updated successfully.",
    "IB870": "Error occurred while updating notification template.",
    "IB871": "Notification Template Already Exists.",
    "IB872": "Error occurred while creating notification actions.",
    "IB873": "Notification actions saved successfully.",
    "IB874": "Please setup notifications for this event.",
    "IB875": "Successfully Changed User IsKYCApprovedFirstLogin Status.",
    "IB876": "Error occurred when changing User IsKYCApprovedFirstLogin status.",
    "IB877": "Savings goals cannot be created without KYC approval.",
    "IB878": "This notification already exists",
    "IB879": "Selected Saving Purpose has been inactivated.",
    "IB880": "Successfully Sent Mobile-Cash Saving Schedule Notifications.",
    "IB881": "Error occurred when sending Mobile-Cash saving schedule notifications.",
    "IB882": "Fund transfer saved successfully! Please click Confirm button to complete the transaction.",
    "IB883": "Invalid credit account.",
    "IB884": "Savings goal target amount cannot exceed.",
    "IB885": "KYC approval required.",
    "IB886": "Could not modify. This purpose already assigned to savings goal.",
    "IB887": "Insufficient saving goal balance.",
    "IB888": "Transaction amount exceeding saving goal balance.",
    "IB889": "Successfully load dashboard.",
    "IB890": "Error in loading dashboard.",
    "IB891": "Error in export to excel.",
    "IB892": "This purpose is already assigned to a goal.",
    "IB893": "No result found",
    "IB894": "Error occurred while loading Mobile-Cash saving random notification.",
    "IB895": "Random notifications saved successfully.",
    "IB896": "Error occurred while saving random notifications.",
    "IB897": "successfully load Mobile-Cash saving random notifications.",
    "IB898": "error in loading Mobile-Cash saving random notifications.",
    "IB899": "successfully load Mobile-Cash saving range details.",
    "IB900": "error in loading Mobile-Cash saving range details.",
    "IB901": "Mobile-Cash Savings KYC  updated Successfully.",
    "IB902": "Error occured when updating Mobile-Cash Savings KYC.",
    "IB903": "Error occurred while loading customer segment.",
    "IB904": "Customer segment saved successfully.",
    "IB905": "Error occurred while saving random notifications.",
    "IB906": "Customer segment updated successfully.",
    "IB907": "Error occurred while updating customer segment.",
    "IB908": "Customer segment deleted successfully.",
    "IB909": "Error occurred while deleting customer segment.",
    "IB910": "This customer segment already exists.",
    "IB911": "This customer segment can not be deleted. Users are already assigned to this customer segment.",
    "IB912": "Error occurred while retrieving Mobile-Cash savings account details",
    "IB913": "Mobile-Cash savings account details retrieved successfully",
    "IB914": "This customer segment can not be inactivated. Users are already assigned to this customer segment.",
    "IB915": "Error occurred while loading link Mobile-Cash savings account.",
    "IB916": "Mobile-Cash account successfully linked with Mobile-Cash savings account.",
    "IB917": "Error occurred while linking Mobile-Cash savings account.",
    "IB918": "Successfully load Mobile-Cash customer details.",
    "IB919": "Error in loading Mobile-Cash customer details.",
    "IB920": "There is no valid Mobile-Cash account for entered account number.",
    "IB921": "This Mobile-Cash account has been already linked.",
    "IB922": "Invalid Meter Number.",
    "IB923": "Error occurred while connecting to Cash Power remote server.",
    "IB924": "Meter number cannot be empty.",
    "IB925": "Missing cash power reference.",
    "IB926": "Insufficient Cash Power vends with mobile cash.",
    "IB927": "Error occurred while printing the voucher.",
    "IB928": "Authentication error Cash Power server.",
    "IB929": "Requested amount is less than the minimum vend amount.",
    "IB930": "Different vend amount requested for same reference.",
    "IB931": "Merchant commission template detail not found.",
}

export default MessageList;